swagger: "2.0"
info:
  version: "0.0.1"
  title: Countries and cities service
host: localhost:3001
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /country:
    x-swagger-router-controller: country
    get:
      description: List of cities by country
      operationId: countries
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WebeserviceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /country/cities:
    x-swagger-router-controller: cities
    get:
      description: List of cities by country
      operationId: citiesByCountry
      parameters:
       - name: country
         in: query
         description: Name of the country
         required: true
         type: string
       - name: page
         in: query
         description: Pagination from 8 in 8
         required: false
         type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/WebeserviceResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  WebeserviceResponse:
    required:
      - data
    properties:
      data:
        type: array
        items:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
